version: '3'
services:
  web:
    build:
      context: .
    command: sh -c "python manager.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7001:8000"

    depends_on:
      - db
      - redis
    env_file:
      .env
    volume:
      - .:/app
  db: 
    image: postgres:14
    enviroment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    volumes:
      - redis data:/data
  
  celery_worker:
    build:
      context: .

    command: celery _A shop_api worker --loglevel=info
    depends_on:
      - redis
    env_file:
      .env
    volumes:
      - .:/app
    

  celery_beat:
    build:
      context: .

    command: celery _A shop_api beat --loglevel=info
    depends_on:
      - redis
    env_file:
      .env
    volumes:
      - .:/app
    

  celery_flower:
    build:
      context: .

    command: celery _A shop_api flower --port=5555
    depends_on:
      - redis
    port:
      - "5556:5555"
    env_file:
      .env
    volumes:
      - .:/app


volumes:
  db-data:
  redis_data:
 